# **Experiment-5** -Titanic Dataset

**AIM:** Construct a classification model using the Bayes classifier using Python Programming.

**Algorithm Description:** The Bayes Classifier is a supervised machine learning algorithm based on Bayes' Theorem.It is mainly used for classification problems.

    P(A∣B)=P(B∣A)⋅P(A) / P(B)

Where:
 * P(A|B) → Posterior probability
 * P(B|A) → Likelihood
 * P(A) → Prior probability
 * P(B) → Evidence
* It is called “Naive” because it assumes that
all features are independent of each other (which may not always be true).

**Working Principle:**
 * Calculate probability of each class
 * Calculate probability of features given class
 * Apply Bayes’ theorem
 * Choose class with highest probability

**Step 1: Import Required Libraries**

In [ ]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB

**Step 2: Load the Titanic Dataset**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
df = pd.read_csv("/content/drive/MyDrive/Datasets/Titanic.csv")

print(df.head(2))
print(df.shape)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
   Passengerid   Age     Fare  Sex  sibsp  zero  zero.1  zero.2  zero.3  \
0            1  22.0   7.2500    0      1     0       0       0       0   
1            2  38.0  71.2833    1      1     0       0       0       0   

   zero.4  ...  zero.12  zero.13  zero.14  Pclass  zero.15  zero.16  Embarked  \
0       0  ...        0        0        0       3        0        0       2.0   
1       0  ...        0        0        0       1        0        0       0.0   

   zero.17  zero.18  2urvived  
0        0        0         0  
1        0        0         1  

[2 rows x 28 columns]
(1309, 28)


**Step 3:Handle Missing Values**
* Naïve Bayes cannot handle missing values.
* Mean → numeric columns
* Mode → categorical column
* Missing values are replaced with statistically meaningful values, making the dataset complete.

In [ ]:
df["Age"] = df["Age"].fillna(df["Age"].mean())
df["Fare"] = df["Fare"].fillna(df["Fare"].mean())
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])

**Step 4: Encode Categorical Variables**

🔹 What we did?

    Converted Sex and Embarked to numeric using LabelEncoder.

🔹 Why we did this?

    Machine learning algorithms cannot work with text data.

🔹 What happens?

    Text categories are mapped to integers:
    Sex → Male = 1, Female = 0
    Embarked → C = 0, Q = 1, S = 2


In [ ]:
le = LabelEncoder()
df["Sex"] = le.fit_transform(df["Sex"])
df["Embarked"] = le.fit_transform(df["Embarked"])

**Step 5:Separate Features and Target**
* Input features (X)
* Output class labels (Y)
* The model learns from X and predicts Y.

In [ ]:
X = df.drop("2urvived", axis=1)
Y = df["2urvived"]

**Step 6:Split Dataset into Training and Testing Sets**
* Split dataset into 70% training and 30% testing.
* The model trains on training data and is evaluated on test data.

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.3, stratify=Y, random_state=42
)

**Step 7:Gaussian Naïve Bayes Model**

🔹Why Gaussian NB?

    Titanic dataset has continuous numeric features.
    Assumes features follow normal distribution.

🔹 What happens internally

    Computes mean & variance for each feature per class
    Uses Bayes theorem to compute class probabilities

🔹 Predictions

    predict() → class labels
    predict_proba() → probability of survival / non-survival

In [ ]:
gnb = GaussianNB()
gnb.fit(X_train, Y_train)
y_pred_class = gnb.predict(X_test)
print("Gaussian Probabilities:\n", gnb.predict_proba(X_test)[:5])

Gaussian Probabilities:
 [[1.00000000e+00 4.99089727e-18]
 [9.34365828e-01 6.56341717e-02]
 [9.73911086e-01 2.60889145e-02]
 [7.69601961e-01 2.30398039e-01]
 [4.29057829e-01 5.70942171e-01]]


In [ ]:
print("Gaussian NB Accuracy:", accuracy_score(Y_test, y_pred_class))
print("classification report:",classification_report(Y_test,y_pred_class))

Gaussian NB Accuracy: 0.7913486005089059
classification report:               precision    recall  f1-score   support

           0       0.85      0.87      0.86       290
           1       0.61      0.56      0.59       103

    accuracy                           0.79       393
   macro avg       0.73      0.72      0.72       393
weighted avg       0.79      0.79      0.79       393



**Step 8:Multinomial Naïve Bayes Model**

🔹 Why Multinomial NB?

    Works well with encoded & count-like features
    Suitable when features represent frequencies

🔹 What happens internally?

    Counts feature occurrences per class
    Computes conditional probabilities

📌 Works here but not theoretically perfect for continuous features.

In [ ]:
mnb = MultinomialNB()
mnb.fit(X_train, Y_train)

y_pred_class = mnb.predict(X_test)
print(mnb.predict(X_test)[:10])

[1 0 0 0 1 1 0 0 1 1]


In [ ]:
y_pred_prob = mnb.predict_proba(X_test)
print(mnb.predict_proba(X_test)[:5])

[[1.55751458e-23 1.00000000e+00]
 [1.00000000e+00 1.25118799e-17]
 [1.00000000e+00 6.69137376e-16]
 [1.00000000e+00 1.55711384e-14]
 [6.44859202e-04 9.99355141e-01]]


In [ ]:
print("Multinomial NB Accuracy:", accuracy_score(Y_test, y_pred_class))
print(classification_report(Y_test, y_pred_class))

Multinomial NB Accuracy: 0.6692111959287532
              precision    recall  f1-score   support

           0       0.81      0.72      0.76       290
           1       0.40      0.52      0.45       103

    accuracy                           0.67       393
   macro avg       0.61      0.62      0.61       393
weighted avg       0.70      0.67      0.68       393



**Step 9:Bernoulli Naïve Bayes Model**

🔹 What we did?

    Converted all features to binary (0/1).

🔹 Why Bernoulli NB?

    Designed for binary features only

🔹 What happens internally?

    Calculates probability of feature presence/absence per class
    Loses magnitude information (e.g., exact age)

In [ ]:
X_binary = (X > 0).astype(int)

Xb_train, Xb_test, Yb_train, Yb_test = train_test_split(
    X_binary, Y, test_size=0.3, stratify=Y, random_state=42
)

**Step 10:Model Evaluation**

In [ ]:
bnb = BernoulliNB()
bnb.fit(Xb_train, Yb_train)

y_pred_class = bnb.predict(Xb_test)
print("Predictions:", y_pred_class[:10])

y_pred_prob = bnb.predict_proba(Xb_test)
print("Probabilities:\n", np.round(y_pred_prob[:5], 2))
print("Bernoulli NB Accuracy:", accuracy_score(Yb_test, y_pred_class))
print(classification_report(Yb_test, y_pred_class))

Predictions: [0 0 1 0 0 0 0 0 1 0]
Probabilities:
 [[0.81 0.19]
 [0.92 0.08]
 [0.45 0.55]
 [0.87 0.13]
 [0.6  0.4 ]]
Bernoulli NB Accuracy: 0.7379134860050891
              precision    recall  f1-score   support

           0       0.79      0.89      0.83       290
           1       0.50      0.32      0.39       103

    accuracy                           0.74       393
   macro avg       0.64      0.60      0.61       393
weighted avg       0.71      0.74      0.72       393



**Among the three Naïve Bayes classifiers, Gaussian Naïve Bayes achieved the best performance for the Titanic dataset as it effectively models continuous and numeric features without loss of information.**

* Gaussian Naïve Bayes performed best
* Multinomial NB gave moderate results
* Bernoulli NB performed the worst