# **EXPERIEMENT-12**
**AIM:**
To implement and evaluate a Hidden Markov Model using the hmmlearn library for sequential pattern recognition and analyze hidden state sequences using decoding, posterior probabilities, sequence likelihood, and sample generation.

**Step 1 — Hidden States and Observations**

* Hidden States (not directly observable)
   * Speech sound categories:
     *  Vowel
     *  Consonant

* Observations (visible features)
  * Acoustic features detected from speech:
     * Low frequency sound
     * Medium frequency sound
     * High frequency sound

In speech recognition systems, we observe acoustic signals, but the actual phoneme category (vowel/consonant) is hidden.

**Step 2 — Initial Probabilities:**

Since we do not know the starting speech sound, we assume equal probability.

           π = [0.5 , 0.5]

Meaning

*  P(Vowel) = 0.5

*  P(Consonant) = 0.5

**Step 3 — Transition Probability Matrix:**

Rows → Current state
Columns → Next state

      A =[0.6  0.4]
         [0.5  0.5]

Meaning
* Vowel → Vowel = 0.6
* Vowel → Consonant = 0.4
* Consonant → Vowel = 0.5
* Consonant → Consonant = 0.5

This represents how speech sounds transition while speaking.

**Step 4 — Emission Probability Matrix**

Rows → Hidden states
Columns → Observations

* Observation mapping

        Low frequency = 0
        Medium frequency = 1
        High frequency = 2

          B =[0.5  0.3  0.2]
             [0.2  0.4  0.4]

Meaning
* If state = Vowel

      Low frequency = 0.5
      Medium frequency = 0.3
      High frequency = 0.2

* If state = Consonant

      Low frequency = 0.2
      Medium frequency = 0.4
      High frequency = 0.4



In [ ]:
#Step 5 — Install hmmlearn in Colab
!pip install hmmlearn
#Import Libraries
import numpy as np
from hmmlearn import hmm
#Step 6 — Build HMM with Fixed Parameters
model = hmm.MultinomialHMM(
    n_components=2,
    n_trials=1,
    init_params="",
    params=""
)
#Set Initial Probabilities
model.startprob_ = np.array([0.5, 0.5])
#Set Transition Matrix
model.transmat_ = np.array([
    [0.6, 0.4],
    [0.5, 0.5]
])
#Set Emission Matrix
model.emissionprob_ = np.array([
    [0.5, 0.3, 0.2],
    [0.2, 0.4, 0.4]
])
#Important for hmmlearn
model.n_features = 3

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 166.0/166.0 kB 6.5 MB/s eta 0:00:00


https://github.com/hmmlearn/hmmlearn/issues/335
https://github.com/hmmlearn/hmmlearn/issues/340


**Step 7 — Example Observation Sequence**

Example acoustic signal sequence
   * Low → Medium → High

Observation mapping

      Low frequency = 0
      Medium frequency = 1
      High frequency = 2

In [ ]:

observations = np.array([
    [1,0,0],  # Low frequency
    [0,1,0],  # Medium frequency
    [0,0,1]   # High frequency
])

**Decode Most Likely Hidden States (Viterbi):**

The Viterbi algorithm finds the most probable sequence of hidden speech states.

In [ ]:
logprob, states = model.decode(observations, algorithm="viterbi")
print("Log Probability:", logprob)
print("Most Likely Hidden States:", states)

Log Probability: -4.828313737302301
Most Likely Hidden States: [0 1 1]


**Posterior Probability of States:**
This computes the probability of each hidden state at every time step.

In [ ]:
posterior = model.predict_proba(observations)
print("Posterior probabilities:\n", posterior)

Posterior probabilities:
 [[0.70689655 0.29310345]
 [0.48275862 0.51724138]
 [0.37931034 0.62068966]]


**Sequence Likelihood:**

This calculates P(O∣λ) the probability of observing the sequence given the model.


likelihood = model.score(observations)

print("Sequence Likelihood:", likelihood)

**Generate Sample SequenceP:**

This generates new observation sequences and hidden states.

In [ ]:
X, Z = model.sample(5)
print("Generated Observations:", X)
print("Generated Hidden States:", Z)

Generated Observations: [[0 0 1]
 [0 1 0]
 [0 0 1]
 [0 1 0]
 [0 1 0]]
Generated Hidden States: [0 1 1 0 0]



**Conclusion :**

This experiment demonstrates how a Hidden Markov Model can analyze sequential speech signals and infer hidden sound categories from observed acoustic features. The model uses probabilistic transitions and emissions to identify the most likely hidden states.